module.exports = Object.freeze({

  // Personal Information
  FIRST_NAME: "FIRST_NAME",  
  LAST_NAME: "LAST_NAME",
  MIDDLE_INITIAL: "MIDDLE_INITIAL",
  SSN: "SSN",
  RANK: "RANK",
  PHONE: "PHONE",

  // POSTING
  PLATOON: "PLATOON",
  COMPANY: "COMPANY",
  BATTALION: "BATTALION",
  BRIGADE: "BRIGADE",
  DIVISION: "DIVISION",
  POST: "POST",
  STATION_ZIP: "STATION_ZIP",
  STATION_PHONE: "STATION_PHONE", 

  // DESTINATION
  STREET: "STREET",
	CITY: "CITY",
	STATE: "STATE",
	ZIP: "ZIP",

	// LEAVE
	TYPE_OF_LEAVE: "TYPE_OF_LEAVE",
	LEAVE_EXPLANATION: "LEAVE_EXPLANATION",
	ACCRUED_LEAVE: "ACCRUED_LEAVE",
	REQUESTED_LEAVE: "REQUESTED_LEAVE",
	ADVANCED_LEAVE: "ADVANCED_LEAVE",
	EXCESS_LEAVE: "EXCESS_LEAVE",

	// LEAVE TYPES
  LEAVE_ORDINARY:   "ORDINARY",
  LEAVE_EMERGENCY:  "EMERGENCY",
  LEAVE_PERMISSIVE: "PERMISSIVE",
  LEAVE_TDY:        "TDY",
  LEAVE_OTHER:      "OTHER",
});